# Generated by Django 5.2.15 on 2026-07-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('soupe', 'Soupe'), ('pizza', 'Pizza'), ('pasta', 'Pasta'), ('desert', 'Desert'), ('wine', 'Wine'), ('beer', 'Beer'), ('drinks', 'Drinks')], max_length=20)),
                ('on_main', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
