# Generated by Django 5.2.15 on 2026-07-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
